name = "example"
language = "c"
compiler = "gcc"
include_paths = ["src/include"]

[[Unit]]
name = "example"
type = "binary"
source = "src/app"
output_directory = "build/bin"
intermediate_directory = "build/obj"
