name = "example"
language = "c"
compiler = "msvc"
include_paths = ['example\src\include']

[[Unit]]
name = "app"
type = "binary"
source = "src/app"
output_directory = "build/bin/"
intermediate_directory = "build/obj/"
