[package]
name = "copper"
version = "0.1.0"
edition = "2021"
authors = ["DuckySmacky"]

[dependencies]
clap = { version = "4.5.40", features = ["cargo", "derive"] }
serde = { version = "1.0.219", features = ["derive"] }
toml = "0.8.23"